#!/usr/bin/env bash
# =============================================
#   archenemy - lib/gen-autostart.sh
#   Generator autostartu aplikacji wybranych w TUI (Super+A → [u]).
#   JEDNO ŹRÓDŁO PRAWDY — source'owane przez:
#     - install/install.sh (krok 8g, generowanie przy instalacji),
#     - scripts/appbinds/autostart-picker.sh (zapis wyboru na żywo).
#   Nie uruchamiaj bezpośrednio — to biblioteka funkcji.
#
#   Warstwa RÓWNOLEGŁA do autostartpersonalisation.lua: tamten plik
#   użytkownik edytuje ręcznie i nikt go nie nadpisuje; ten jest w całości
#   generowany z data/autostart-apps.dat (lista ID .desktop, jedno na linię).
# =============================================

# Argumenty: <plik-danych .dat> <plik-wyjściowy .lua>
generate_autostart_apps() {
    local dat="$1" out="$2"
    local -a apps=()
    local id

    if [[ -f "$dat" ]]; then
        while IFS= read -r id; do
            # Puste linie i komentarze pomijamy — plik bywa ruszany ręcznie.
            [[ -z "$id" || "$id" == \#* ]] && continue
            apps+=("$id")
        done < "$dat"
    fi

    {
        echo "-- generated by archenemy install.sh"
        if [[ ${#apps[@]} -eq 0 ]]; then
            echo "-- Brak wybranych aplikacji — Super+A → [u] autostart apps"
        else
            echo "-- Zarządzane przez Super+A -> [u] autostart apps. Nie edytuj ręcznie —"
            echo "-- zmiany przepadną przy następnym zapisie z TUI."
            echo "hl.on(\"hyprland.start\", function()"
            for id in "${apps[@]}"; do
                echo "    hl.exec_cmd(\"gtk-launch $id\")"
            done
            echo "end)"
        fi
    } > "$out"
}
