#!/usr/bin/env bash
# =============================================
#   archenemy - lib/gen-workspaces.sh
#   Generator reguł i bindów workspace'ów wg trybu (shared/decades).
#   JEDNO ŹRÓDŁO PRAWDY — source'owane przez:
#     - install/install.sh (krok 8b, generowanie przy instalacji),
#     - scripts/hypr/workspace-mode-switch.sh (przełączanie na żywo, Super+A).
#   Nie uruchamiaj bezpośrednio — to biblioteka funkcji.
#
#   shared:  10 globalnych workspace'ów; monitor k (L→P) = dom workspace'a k.
#   decades: dekady 10N+i wyświetlane jako 1-10 (defaultName). Panel wbudowany
#     (eDP/LVDS/DSI) MUSI dostać pierwszą dekadę niezależnie od numeracji — to
#     jedyny monitor, który istnieje zawsze; gdyby 1-10 dostał zewnętrzny, sesja
#     bez niego tworzyłaby sieroty (podwójna „1" na pasku). ORDER steruje wtedy
#     kolejnością dekad monitorów ZEWNĘTRZNYCH. Rola primary/secondary dalej
#     rządzi TYLKO tapetami v1/v2 (rofi_wallpaper_switcher.sh).
#   Bindy Super+1..0 i scroll zależą od trybu, więc SĄ GENEROWANE tutaj
#   (warstwa maszynowa), a nie trzymane w tracked workspaces.conf.
# =============================================

is_internal_panel() { [[ "$1" == eDP* || "$1" == LVDS* || "$1" == DSI* ]]; }

# Wydzielone do funkcji, żeby dało się mock-testować bez całego instalatora.
# Argumenty: <plik-wyjściowy> <tryb> <monitory w kolejności ORDER (L→P)...>
generate_workspaces_monitors() {
    local out="$1" mode="$2"
    shift 2
    local -a mons_lr=("$@")
    local mon k i ws ws_base rule
    local -a ordered=()

    {
        echo "# generated by archenemy install.sh"
        echo "# Tryb workspace'ów: $mode (patrz data/workspace-mode.dat)."
        if [[ "$mode" == "shared" ]]; then
            echo "# shared: 10 globalnych workspace'ów; monitor k (L→P) = dom workspace'a k."
            k=1
            for mon in "${mons_lr[@]}"; do
                echo ""
                echo "# monitor $k: $mon — domowy workspace $k"
                echo "workspace = $k, monitor:$mon, default:true"
                k=$((k + 1))
            done
            cat <<'BINDS'

# ─── Bindy nawigacji (shared: globalne workspace'y) ───
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Cykliczne przewijanie — globalne (e±1 = następny/poprzedni istniejący)
bind = $mainMod CTRL, left,  workspace, e-1
bind = $mainMod CTRL, right, workspace, e+1
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up,   workspace, e-1
BINDS
        else
            echo "# decades: dekady po 10 na monitor; drugi i kolejne monitory wyświetlają"
            echo "# 11-20 (21-30, ...) jako 1-10 przez defaultName. Panel wbudowany zawsze"
            echo "# ma pierwszą dekadę; kolejność zewnętrznych wg numeracji L→P (ORDER)."
            for mon in "${mons_lr[@]}"; do
                is_internal_panel "$mon" && ordered+=("$mon")
            done
            for mon in "${mons_lr[@]}"; do
                is_internal_panel "$mon" || ordered+=("$mon")
            done
            ws_base=0
            for mon in "${ordered[@]}"; do
                echo ""
                echo "# $mon — workspace'y $((ws_base+1))-$((ws_base+10))"
                for i in $(seq 1 10); do
                    ws=$((ws_base + i))
                    rule="workspace = $ws, monitor:$mon"
                    [[ $i -eq 1 ]] && rule+=", default:true"
                    [[ $ws_base -gt 0 ]] && rule+=", defaultName:$i"
                    echo "$rule"
                done
                ws_base=$((ws_base + 10))
            done
            cat <<'BINDS'

# ─── Bindy nawigacji (decades: względem monitora z fokusem) ───
bind = $mainMod, 1, workspace, r~1
bind = $mainMod, 2, workspace, r~2
bind = $mainMod, 3, workspace, r~3
bind = $mainMod, 4, workspace, r~4
bind = $mainMod, 5, workspace, r~5
bind = $mainMod, 6, workspace, r~6
bind = $mainMod, 7, workspace, r~7
bind = $mainMod, 8, workspace, r~8
bind = $mainMod, 9, workspace, r~9
bind = $mainMod, 0, workspace, r~10

bind = $mainMod SHIFT, 1, movetoworkspace, r~1
bind = $mainMod SHIFT, 2, movetoworkspace, r~2
bind = $mainMod SHIFT, 3, movetoworkspace, r~3
bind = $mainMod SHIFT, 4, movetoworkspace, r~4
bind = $mainMod SHIFT, 5, movetoworkspace, r~5
bind = $mainMod SHIFT, 6, movetoworkspace, r~6
bind = $mainMod SHIFT, 7, movetoworkspace, r~7
bind = $mainMod SHIFT, 8, movetoworkspace, r~8
bind = $mainMod SHIFT, 9, movetoworkspace, r~9
bind = $mainMod SHIFT, 0, movetoworkspace, r~10

# Cykliczne przewijanie — w obrębie dekady monitora z fokusem (r±1)
bind = $mainMod CTRL, left,  workspace, r-1
bind = $mainMod CTRL, right, workspace, r+1
bind = $mainMod, mouse_down, workspace, r+1
bind = $mainMod, mouse_up,   workspace, r-1
BINDS
        fi
    } > "$out"
}
