#!/usr/bin/env bash
# =============================================
#   archenemy - lib/gen-workspaces.sh
#   Generator reguł i bindów workspace'ów wg trybu (shared/decades).
#   JEDNO ŹRÓDŁO PRAWDY — source'owane przez:
#     - install/install.sh (krok 8b, generowanie przy instalacji),
#     - scripts/hypr/workspace-mode-switch.sh (przełączanie na żywo, Super+A).
#   Nie uruchamiaj bezpośrednio — to biblioteka funkcji.
#
#   Od migracji na Lua (Hyprland 0.55+) emituje workspaces-monitors.lua
#   (hl.workspace_rule / hl.bind zamiast hyprlang).
#   INWARIANT FORMATU: każda reguła hl.workspace_rule w JEDNEJ linii,
#   zaczynającej się od `hl.workspace_rule({ workspace = "N", monitor = "M"`
#   — parsuje ją sedem workspace-orphan-guard.sh. Zmieniasz format tutaj →
#   zmieniasz wzorzec seda w guardzie.
#
#   shared:  10 globalnych workspace'ów; monitor k (L→P) = dom workspace'a k.
#   decades: dekady 10N+i wyświetlane jako 1-10 (default_name). Panel wbudowany
#     (eDP/LVDS/DSI) MUSI dostać pierwszą dekadę niezależnie od numeracji — to
#     jedyny monitor, który istnieje zawsze; gdyby 1-10 dostał zewnętrzny, sesja
#     bez niego tworzyłaby sieroty (podwójna „1" na pasku). ORDER steruje wtedy
#     kolejnością dekad monitorów ZEWNĘTRZNYCH. Rola primary/secondary dalej
#     rządzi TYLKO tapetami v1/v2 (rofi_wallpaper_switcher.sh).
#   Bindy Super+1..0 i scroll zależą od trybu, więc SĄ GENEROWANE tutaj
#   (warstwa maszynowa), a nie trzymane w tracked workspaces.lua.
# =============================================

is_internal_panel() { [[ "$1" == eDP* || "$1" == LVDS* || "$1" == DSI* ]]; }

# Wydzielone do funkcji, żeby dało się mock-testować bez całego instalatora.
# Argumenty: <plik-wyjściowy> <tryb> <monitory w kolejności ORDER (L→P)...>
generate_workspaces_monitors() {
    local out="$1" mode="$2"
    shift 2
    local -a mons_lr=("$@")
    local mon k i ws ws_base rule
    local -a ordered=()

    {
        echo "-- generated by archenemy install.sh"
        echo "-- Tryb workspace'ów: $mode (patrz data/workspace-mode.dat)."
        echo "local mainMod = \"SUPER\""
        if [[ "$mode" == "shared" ]]; then
            echo "-- shared: 10 globalnych workspace'ów; monitor k (L→P) = dom workspace'a k."
            k=1
            for mon in "${mons_lr[@]}"; do
                echo ""
                echo "-- monitor $k: $mon — domowy workspace $k"
                echo "hl.workspace_rule({ workspace = \"$k\", monitor = \"$mon\", default = true })"
                k=$((k + 1))
            done
            cat <<'BINDS'

-- ─── Bindy nawigacji (shared: globalne workspace'y) ───
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = "1" }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = "2" }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = "3" }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = "4" }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = "5" }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = "6" }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = "7" }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = "8" }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = "9" }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = "10" }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = "1", follow = true }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = "2", follow = true }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = "3", follow = true }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = "4", follow = true }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = "5", follow = true }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = "6", follow = true }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = "7", follow = true }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = "8", follow = true }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = "9", follow = true }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = "10", follow = true }))

-- Cykliczne przewijanie — globalne (e±1 = następny/poprzedni istniejący)
hl.bind(mainMod .. " + CTRL + left", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
BINDS
        else
            echo "-- decades: dekady po 10 na monitor; drugi i kolejne monitory wyświetlają"
            echo "-- 11-20 (21-30, ...) jako 1-10 przez default_name. Panel wbudowany zawsze"
            echo "-- ma pierwszą dekadę; kolejność zewnętrznych wg numeracji L→P (ORDER)."
            for mon in "${mons_lr[@]}"; do
                is_internal_panel "$mon" && ordered+=("$mon")
            done
            for mon in "${mons_lr[@]}"; do
                is_internal_panel "$mon" || ordered+=("$mon")
            done
            ws_base=0
            for mon in "${ordered[@]}"; do
                echo ""
                echo "-- $mon — workspace'y $((ws_base+1))-$((ws_base+10))"
                for i in $(seq 1 10); do
                    ws=$((ws_base + i))
                    rule="hl.workspace_rule({ workspace = \"$ws\", monitor = \"$mon\""
                    [[ $i -eq 1 ]] && rule+=", default = true"
                    [[ $ws_base -gt 0 ]] && rule+=", default_name = \"$i\""
                    rule+=" })"
                    echo "$rule"
                done
                ws_base=$((ws_base + 10))
            done
            cat <<'BINDS'

-- ─── Bindy nawigacji (decades: względem monitora z fokusem) ───
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = "r~1" }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = "r~2" }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = "r~3" }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = "r~4" }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = "r~5" }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = "r~6" }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = "r~7" }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = "r~8" }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = "r~9" }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = "r~10" }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = "r~1", follow = true }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = "r~2", follow = true }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = "r~3", follow = true }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = "r~4", follow = true }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = "r~5", follow = true }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = "r~6", follow = true }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = "r~7", follow = true }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = "r~8", follow = true }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = "r~9", follow = true }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = "r~10", follow = true }))

-- Cykliczne przewijanie — w obrębie dekady monitora z fokusem (r±1)
hl.bind(mainMod .. " + CTRL + left", hl.dsp.focus({ workspace = "r-1" }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.focus({ workspace = "r+1" }))
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "r+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "r-1" }))
BINDS
        fi
    } > "$out"
}
