#!/bin/bash
# =============================================
#   archenemy - tests/appbinds.sh
#   Testy listy i usuwania bindów TUI Super+A (scripts/appbinds/lib/binds.sh)
#   na tymczasowym appbinds.lua. Bez Hyprlanda, bez zapisu poza mktemp.
#
#   Powód powstania (audyt 2026-09-25): lista numerowała tylko linie w formacie
#   TUI, a usuwanie liczyło każde `^hl.bind(` — po ręcznie dopisanym bindzie
#   w innej formie „[d] N” kasowało inną linię niż pokazaną.
#   Uruchom: bash tests/appbinds.sh   (kod 0 = wszystko przeszło)
# =============================================

# shellcheck disable=SC2016,SC2034  # check() robi eval na cytowanym wyrażeniu (zmienne żyją w eval)
set -uo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

PASS=0; FAIL=0
ok()   { PASS=$((PASS + 1)); echo "  ✓ $1"; }
fail() { FAIL=$((FAIL + 1)); echo "  ✗ $1"; }
check() { if eval "$2"; then ok "$1"; else fail "$1"; fi; }

# shellcheck source=../scripts/appbinds/lib/binds.sh
source "$REPO/scripts/appbinds/lib/binds.sh"
BINDS_CONF="$T/appbinds.lua"

# Plik jak po install.sh + dwa bindy z TUI, między nimi bind dopisany ręcznie
# w innej formie (mod dosłownie, exec zamiast exec_cmd) — TUI go nie pokazuje.
write_conf() {
    cat > "$BINDS_CONF" <<'EOF'
-- generated by archenemy install.sh
-- Your app shortcuts — edit via Super+A (scripts/appbinds/appbinds.sh).
local mainMod = "SUPER"
hl.bind(mainMod .. " + g", hl.dsp.exec_cmd("gimp"))
hl.bind("SUPER + x", hl.dsp.exec("xterm"))
hl.bind(mainMod .. " + b", hl.dsp.exec_cmd("alacritty -e btop"))
hl.bind(mainMod .. " + s", hl.dsp.exec_cmd("steam"))
EOF
}

echo "== lista: tylko bindy w formacie TUI, z numerami linii pliku"
write_conf
lines="$(user_bind_lines "$BINDS_CONF")"
check "3 wpisy (obcy hl.bind pominięty)"       '[[ "$(bind_count "$BINDS_CONF")" == 3 ]]'
check "numer linii<TAB>klawisz<TAB>komenda"     '[[ "$lines" == $'"'"'4\tg\tgimp\n6\tb\talacritty -e btop\n7\ts\tsteam'"'"' ]]'
out="$(list_binds)"
check "list_binds numeruje 1..3"                '[[ "$out" == *" 1) Super + g "* && "$out" == *" 2) Super + b "* && "$out" == *" 3) Super + s "* ]]'
check "list_binds nie pokazuje obcego bindu"    '[[ "$out" != *xterm* ]]'
check "brak pliku = zero bindów, kod 0"         '[[ -z "$(user_bind_lines "$T/nie-ma")" && "$(bind_count "$T/nie-ma")" == 0 ]]'

echo "== usuwanie: [d] N kasuje dokładnie linię pokazaną jako N"
write_conf
remove_bind_by_index "$BINDS_CONF" 2
check "usunięty bind nr 2 (btop), nie linia 5"  '! grep -q btop "$BINDS_CONF" && grep -q xterm "$BINDS_CONF"'
check "pozostałe bindy nietknięte"              '[[ "$(user_bind_lines "$BINDS_CONF")" == $'"'"'4\tg\tgimp\n6\ts\tsteam'"'"' ]]'
check "obcy bind i nagłówek zostają"            '[[ "$(wc -l < "$BINDS_CONF")" == 6 && "$(sed -n 3p "$BINDS_CONF")" == "local mainMod = \"SUPER\"" ]]'

write_conf
remove_bind_by_index "$BINDS_CONF" 3
check "usunięty bind nr 3 (steam) — ostatni"    '! grep -q steam "$BINDS_CONF" && [[ "$(bind_count "$BINDS_CONF")" == 2 ]]'

write_conf
before="$(cat "$BINDS_CONF")"
check "numer spoza listy → kod 1, plik bez zmian" '! remove_bind_by_index "$BINDS_CONF" 4 && [[ "$(cat "$BINDS_CONF")" == "$before" ]]'
check "numer 0 / nie-liczba → kod 1"            '! remove_bind_by_index "$BINDS_CONF" 0 && ! remove_bind_by_index "$BINDS_CONF" abc && [[ "$(cat "$BINDS_CONF")" == "$before" ]]'

echo ""
echo "Wynik: $PASS ✓ / $FAIL ✗"
[[ $FAIL -eq 0 ]]
