#!/bin/bash

# =============================================
#   archenemy - appbinds.sh
#   Terminalowy menedżer skrótów do aplikacji (Super + klawisz).
#   Otwierany przez Super+A (pływające okno alacritty).
#   UI po angielsku (decyzja właściciela 2026-07-12).
#
#   Bindy lądują w warstwie OSOBISTEJ (poza gitem):
#   ~/archenemy/config/hypr/appbinds.lua
#   — hyprland.lua rice'a require'uje ten plik.
# =============================================

ARCHENEMY_DIR="$HOME/archenemy"
BINDS_CONF="$ARCHENEMY_DIR/config/hypr/appbinds.lua"
CONFIG_DIR="$HOME/.config"

# Pliki, w których klawisz może już być zajęty (bindy Super+klawisz archenemy).
# workspaces-monitors.lua: od 2026-07-17 bindy Super+1..0 są GENEROWANE tam
# (zależą od trybu shared/decades) — bez tego wpisu TUI pozwoliłoby przykryć
# nawigację workspace'ów własnym bindem.
CONFLICT_FILES=(
    "$CONFIG_DIR/hypr/hyprland.lua"
    "$ARCHENEMY_DIR/config/hypr/workspaces.lua"
    "$ARCHENEMY_DIR/config/hypr/workspaces-monitors.lua"
    "$BINDS_CONF"
)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Czysty bashowy trim — NIE `| xargs`: xargs robi przetwarzanie cudzysłowów,
# więc `sh -c 'btop; read'` gubił apostrofy, a samotny apostrof wysypywał
# cały pipe („unmatched single quote" → „Empty command").
trim() {
    local s="$1"
    s="${s#"${s%%[![:space:]]*}"}"
    s="${s%"${s##*[![:space:]]}"}"
    printf '%s' "$s"
}

# Jeden klawisz bez Enter (menu/potwierdzenia — nie wolne wpisywanie tekstu).
# Zwraca $'\e' dla samego Escape, żeby wołający mógł potraktować go jak
# anulowanie/wyjście.
read_key() {
    local prompt="$1" key=""
    IFS= read -rsn1 -p "$prompt" key
    echo "" >&2
    printf '%s' "$key"
}

# Zapis jednowartościowego pliku warstwy maszynowej (data/*.dat) — atomowo
# (tmp + mv), bo moduły waybara czytają te pliki co sekundę i nie mogą trafić
# na zapis w połowie. Jedno miejsce dla wszystkich menu TUI.
write_dat() {
    local file="$1" value="$2" tmp
    mkdir -p "$(dirname "$file")"
    tmp="$(mktemp "${file}.XXXXXX")" || { echo -e "  ${RED}✗ mktemp failed.${NC}"; return 1; }
    printf '%s\n' "$value" > "$tmp"
    mv "$tmp" "$file"
}

# ─── PLIK BINDÓW ──────────────────────────────────────────────────────────────

# Upewnij się, że plik istnieje (install.sh go tworzy, ale nie zakładaj)
ensure_conf() {
    [[ -f "$BINDS_CONF" ]] && return
    mkdir -p "$(dirname "$BINDS_CONF")"
    # local mainMod jest konieczny: require() = osobny scope Lua, plik nie
    # widzi zmiennych z hyprland.lua rice'a.
    {
        echo "-- generated by archenemy install.sh"
        echo "-- Your app shortcuts — edit via Super+A (scripts/appbinds/appbinds.sh)."
        echo "local mainMod = \"SUPER\""
    } > "$BINDS_CONF"
}

# Czy klawisz jest już zajęty przez jakikolwiek bind Super+klawisz?
# (bez dodatkowych modyfikatorów — SUPER SHIFT itd. nie koliduje)
key_taken() {
    local key="$1"
    # Dwa warianty emisji: `hl.bind(mainMod .. " + KEY", ...` (configi archenemy)
    # oraz `hl.bind("SUPER + KEY", ...` (gdyby ktoś wpisał moda dosłownie).
    grep -hqiE "^hl\\.bind\\((mainMod[[:space:]]*\\.\\.[[:space:]]*\" \\+ ${key}\"|\"SUPER \\+ ${key}\")," \
        "${CONFLICT_FILES[@]}" 2>/dev/null
}

# Wypisz obecne bindy użytkownika, ponumerowane
list_binds() {
    local i=0 key cmd
    while IFS= read -r line; do
        # hl.bind(mainMod .. " + KEY", hl.dsp.exec_cmd("CMD"))
        [[ "$line" =~ ^hl\.bind\(mainMod[[:space:]]*\.\.[[:space:]]*\"\ \+\ ([A-Za-z0-9_]+)\",[[:space:]]*hl\.dsp\.exec_cmd\(\"(.*)\"\)\) ]] || continue
        i=$((i + 1))
        key="${BASH_REMATCH[1]}"
        cmd="${BASH_REMATCH[2]}"
        printf "    ${CYAN}%2d)${NC} Super + ${BLUE}%-12s${NC} → %s\n" "$i" "$key" "$cmd"
    done < "$BINDS_CONF"
    if [[ $i -eq 0 ]]; then
        echo -e "    ${YELLOW}(no custom binds yet — add your first!)${NC}"
    fi
    return 0
}

# Przeładuj Hyprlanda, żeby bind działał od razu
reload_hyprland() {
    if command -v hyprctl &>/dev/null; then
        hyprctl reload &>/dev/null
        echo -e "  ${GREEN}✓ Hyprland reloaded — the bind works immediately.${NC}"
    else
        echo -e "  ${YELLOW}⚠ hyprctl unavailable — reload Hyprland manually.${NC}"
    fi
}

# ─── PODGLĄD WSZYSTKICH SKRÓTÓW ──────────────────────────────────────────────

# Ładna nazwa klawisza (mysz, scroll) — reszta zostaje jak w configu
pretty_key() {
    case "$1" in
        mouse:272)  echo "LMB" ;;
        mouse:273)  echo "RMB" ;;
        mouse_down) echo "scroll ↓" ;;
        mouse_up)   echo "scroll ↑" ;;
        *)          echo "$1" ;;
    esac
}

# Wypisz bindy z jednego pliku configu Lua, po jednej linii.
# Konwencja repo: JEDEN bind = JEDNA linia `hl.bind(...)`. Komentarzy --
# nie ucinamy na ślepo (komendy zawierają "--", np. --clipboard-only) —
# strukturę wyciąga regex, ogon linii jest ignorowany.
print_binds_from() {
    local file="$1"
    [[ -f "$file" ]] || return 0
    local line keys rest combo action var

    while IFS= read -r line; do
        # 1. argument hl.bind: mainMod .. " + KEY" albo dosłowny "KEYS"
        if [[ "$line" =~ ^hl\.bind\(mainMod[[:space:]]*\.\.[[:space:]]*\"([^\"]*)\",[[:space:]]*(.*)$ ]]; then
            keys="SUPER${BASH_REMATCH[1]}"
            rest="${BASH_REMATCH[2]}"
        elif [[ "$line" =~ ^hl\.bind\(\"([^\"]*)\",[[:space:]]*(.*)$ ]]; then
            keys="${BASH_REMATCH[1]}"
            rest="${BASH_REMATCH[2]}"
        else
            continue
        fi

        # "SUPER + SHIFT + F" → "Super+SHIFT+F"; myszy/scroll przez pretty_key
        combo="${keys// + /+}"
        combo="${combo/#SUPER/Super}"
        combo="${combo/mouse:272/$(pretty_key mouse:272)}"
        combo="${combo/mouse:273/$(pretty_key mouse:273)}"
        combo="${combo/mouse_down/$(pretty_key mouse_down)}"
        combo="${combo/mouse_up/$(pretty_key mouse_up)}"

        # exec_cmd("...") → pokaż polecenie; exec_cmd(zmienna) → rozwiń z
        # hyprland.lua; inne dyspozytory → pokaż wywołanie hl.dsp bez opcji bindu
        if [[ "$rest" =~ ^hl\.dsp\.exec_cmd\(\"([^\"]*)\"\) ]]; then
            action="${BASH_REMATCH[1]}"
        elif [[ "$rest" =~ ^hl\.dsp\.exec_cmd\(([A-Za-z_][A-Za-z0-9_]*)\) ]]; then
            var="${BASH_REMATCH[1]}"
            action="${HYPR_VARS[$var]:-\$$var}"
        else
            action="${rest#hl.dsp.}"
            action="${action%, \{*}"        # utnij opcje bindu ({ repeating = ... })
            action="${action%% -- *}"        # utnij komentarz Lua za bindem
            [[ "$action" == *"))" ]] && action="${action%)}"  # domykający nawias hl.bind
        fi

        printf "    %-24s %s\n" "$combo" "$action"
    done < "$file"
}

# Pełna lista: rice + warstwy wspólne/maszynowe/osobiste, przez pager
show_all_binds() {
    # Definicje zmiennych (local terminal = "alacritty" itd.) z aktywnego
    # hyprland.lua rice'a.
    declare -gA HYPR_VARS=()
    local line
    # Guard [[ -f ]]: przed pierwszym przełączeniem rice'a hyprland.lua bywa
    # wiszącym symlinkiem — redirect z niego wysypałby całe [s].
    if [[ -f "$CONFIG_DIR/hypr/hyprland.lua" ]]; then
        while IFS= read -r line; do
            if [[ "$line" =~ ^local[[:space:]]+([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=[[:space:]]*\"(.*)\" ]]; then
                HYPR_VARS[${BASH_REMATCH[1]}]="${BASH_REMATCH[2]}"
            fi
        done < "$CONFIG_DIR/hypr/hyprland.lua"
    fi

    {
        echo -e "${BLUE}  All archenemy shortcuts${NC}  (q = back)"
        echo ""
        echo -e "${CYAN}  ── Rice (hyprland.lua) ──${NC}"
        print_binds_from "$CONFIG_DIR/hypr/hyprland.lua"
        echo ""
        echo -e "${CYAN}  ── Workspaces ──${NC}"
        # Bindy workspace'ów są generowane per tryb (shared/decades) do pliku
        # maszynowego; tracked workspaces.lua trzyma już tylko autostart guarda.
        print_binds_from "$ARCHENEMY_DIR/config/hypr/workspaces-monitors.lua"
        echo ""
        echo -e "${CYAN}  ── Multimedia ──${NC}"
        print_binds_from "$ARCHENEMY_DIR/config/hypr/keyboard.lua"
        echo ""
        echo -e "${CYAN}  ── Hardware (this machine) ──${NC}"
        print_binds_from "$ARCHENEMY_DIR/config/hypr/hardware-keys.lua"
        echo ""
        echo -e "${CYAN}  ── Your binds (Super+A) ──${NC}"
        print_binds_from "$BINDS_CONF"
    } | { command -v less &>/dev/null && less -R || cat; }
}

# ─── AKCJE ────────────────────────────────────────────────────────────────────

add_bind() {
    echo ""
    read -rp "  Key (e.g. g, F5, semicolon, minus): " key
    key=$(trim "$key")

    if [[ -z "$key" ]]; then
        echo -e "  ${YELLOW}⚠ Empty key — cancelled.${NC}"
        return
    fi
    # Nazwa keysym Hyprlanda: litera/cyfra albo nazwa bez spacji i przecinków
    if [[ ! "$key" =~ ^[A-Za-z0-9_]+$ ]]; then
        echo -e "  ${RED}✗ '${key}' does not look like a key name (no spaces or commas).${NC}"
        return
    fi
    # Klawisze-modyfikatory dokładają własny mod do maski w chwili naciśnięcia,
    # więc prosty bind Super+<modyfikator> nigdy nie odpali (wiki: Binding modkeys
    # only) — odrzucamy, zamiast pozwolić na martwy bind.
    if [[ "$key" =~ ^(Shift|Control|Alt|Super|Meta|Hyper)_(L|R)$ ]]; then
        echo -e "  ${RED}✗ '${key}' is a modifier key — a plain Super+${key} bind would never fire.${NC}"
        return
    fi
    if key_taken "$key"; then
        echo -e "  ${RED}✗ Super+${key} is already taken (by archenemy or one of your binds).${NC}"
        return
    fi

    read -rp "  Command (e.g. spotify, steam, alacritty -e btop): " cmd
    cmd=$(trim "$cmd")
    if [[ -z "$cmd" ]]; then
        echo -e "  ${YELLOW}⚠ Empty command — cancelled.${NC}"
        return
    fi
    # Komenda ląduje w stringu Lua — cudzysłów/backslash rozbiłyby składnię pliku.
    if [[ "$cmd" == *'"'* || "$cmd" == *'\'* ]]; then
        echo -e "  ${RED}✗ Command must not contain \" or \\ (it is written into a Lua string).${NC}"
        return
    fi

    # Ostrzeż, jeśli program nie jest zainstalowany (bind i tak można dodać)
    local bin="${cmd%% *}"
    if ! command -v "$bin" &>/dev/null; then
        echo -e "  ${YELLOW}⚠ '${bin}' not found in PATH.${NC}"
        read -rp "  Add anyway? [y/N]: " ans
        [[ "$ans" =~ ^[Yy]$ ]] || return
    fi

    echo "hl.bind(mainMod .. \" + $key\", hl.dsp.exec_cmd(\"$cmd\"))" >> "$BINDS_CONF"
    echo -e "  ${GREEN}✓ Added: Super+${key} → ${cmd}${NC}"
    reload_hyprland
}

remove_bind() {
    # Zbierz numery linii z bindami, w kolejności wyświetlania
    mapfile -t BIND_LINES < <(grep -n '^hl\.bind(' "$BINDS_CONF" | cut -d: -f1)
    if [[ ${#BIND_LINES[@]} -eq 0 ]]; then
        echo -e "  ${YELLOW}⚠ Nothing to remove.${NC}"
        return
    fi

    echo ""
    read -rp "  Bind number to remove (Enter = cancel): " num
    [[ -z "$num" ]] && return
    if [[ ! "$num" =~ ^[0-9]+$ ]] || (( num < 1 || num > ${#BIND_LINES[@]} )); then
        echo -e "  ${RED}✗ There is no bind number '${num}'.${NC}"
        return
    fi

    sed -i "${BIND_LINES[$((num - 1))]}d" "$BINDS_CONF"
    echo -e "  ${GREEN}✓ Removed.${NC}"
    reload_hyprland
}

# ─── TRYB WORKSPACE'ÓW (shared/decades) ──────────────────────────────────────

# Przełączenie trybu na żywo (bez ponownego install.sh). Cała robota —
# regeneracja workspaces-monitors.lua, reload, guard — siedzi w
# scripts/hypr/workspace-mode-switch.sh (jedno źródło prawdy z install.sh).
workspace_mode_menu() {
    local mode_dat="$ARCHENEMY_DIR/data/workspace-mode.dat"
    local switch="$ARCHENEMY_DIR/scripts/hypr/workspace-mode-switch.sh"
    local cur="decades"
    [[ -f "$mode_dat" ]] && cur="$(<"$mode_dat")"
    local other="shared"; [[ "$cur" == "shared" ]] && other="decades"

    echo ""
    echo -e "  Current workspace mode: ${CYAN}${cur}${NC}"
    echo -e "    ${BLUE}shared${NC}  — 10 global workspaces (1-10) shared by all monitors"
    echo -e "    ${BLUE}decades${NC} — each monitor gets its own 1-10 (isolated decades)"
    echo ""
    local ans; ans="$(read_key "  Switch to '${other}'? [y/N]: ")"
    [[ "$ans" =~ ^[Yy]$ ]] || { echo -e "  ${YELLOW}Cancelled.${NC}"; return; }

    if [[ ! -x "$switch" ]]; then
        echo -e "  ${RED}✗ Missing ${switch} — run ./install/install.sh once.${NC}"
        return
    fi
    bash "$switch" "$other"
}

# ─── STYL PASKA GŁOŚNOŚCI (waybar) ───────────────────────────────────────────

# Wybór stylu paska custom/volumebar (line/ticks/solid). Zapis do
# data/volume-bar-style.dat (czyta go scripts/waybar/volume-bar.sh), potem
# sygnał 10 do waybara = pasek przerysowuje się od razu.
volume_style_menu() {
    local style_dat="$ARCHENEMY_DIR/data/volume-bar-style.dat"
    local cur="line"
    [[ -f "$style_dat" ]] && cur="$(<"$style_dat")"
    cur="${cur//[[:space:]]/}"
    # Ta sama interpretacja co w volume-bar.sh: wszystko poza "ticks"/"solid"
    # (w tym nazwy stylów wycofanych 2026-09-03) jest efektywnie "line" — menu
    # nie może pokazywać stylu, którego skrypt już nie zna.
    [[ "$cur" == "ticks" || "$cur" == "solid" ]] || cur="line"

    echo ""
    echo -e "  Volume bar style (waybar): ${CYAN}${cur}${NC}"
    echo -e "    ${BLUE}1${NC}) line    ━━━━━━────"
    echo -e "    ${BLUE}2${NC}) ticks   ▮▮▮▮▮▮▯▯▯▯"
    echo -e "    ${BLUE}3${NC}) solid   ▬▬▬▬▬▬▬▬▬▬▬▬────────"
    echo ""
    local ans; ans="$(read_key "  Choose [1-3, Esc = cancel]: ")"
    local target=""
    case "$ans" in
        1) target="line" ;;
        2) target="ticks" ;;
        3) target="solid" ;;
        ""|$'\e') echo -e "  ${YELLOW}Cancelled.${NC}"; return ;;
        *)  echo -e "  ${RED}✗ Pick 1, 2 or 3.${NC}"; return ;;
    esac

    write_dat "$style_dat" "$target" || return
    pkill -RTMIN+10 waybar 2>/dev/null
    echo -e "  ${GREEN}✓ Volume bar style: ${target}${NC}"
}

# ─── WYJŚCIE AUDIO mpd (pipewire / alsa) ─────────────────────────────────────

# Przełącznik wyjścia mpd — Super+A → [o]. Pipewire jest ZALECANE (miksuje się
# z pulpitem, klawisze głośności działają, tapety ♪ flux-walla słyszą muzykę).
# ALSA `hw:` to tryb WYŁĄCZNY: dopóki mpd trzyma kartę, reszta pulpitu może
# stracić dźwięk — dlatego ostrzeżenie, test odtwarzania po przełączeniu
# i automatyczny powrót na pipewire, gdy ALSA nie ruszy. To menu NIGDY nie
# zatrzymuje pipewire/wireplumbera (zepsułoby dźwięk całego pulpitu).
# Mechanizm: config/mpd/output.conf (warstwa maszynowa, wczytywany przez
# mpd.conf `include`) + restart usługi użytkownika. Nie da się tego zrobić
# przez `mpc enable/disable`: state_file mpd (src/output/State.cxx) przy
# odczycie tylko WYŁĄCZA wyjścia, więc wybór nie przeżyłby restartu.
MPD_OUTPUT_CONF="$ARCHENEMY_DIR/config/mpd/output.conf"
MPD_OUTPUT_DAT="$ARCHENEMY_DIR/data/mpd-output.dat"
# Katalog /proc/asound — zmienna tylko po to, żeby testy na atrapie mogły go podmienić.
ASOUND_DIR="${ARCHENEMY_ASOUND_DIR:-/proc/asound}"

# Wypisz urządzenia PCM do odtwarzania z /proc/asound (bez alsa-utils):
# linie "hw:C,D<TAB>nazwa karty — nazwa PCM". /proc/asound/pcm ma format
# "CC-DD: nazwa : typ : playback N : capture N".
list_alsa_playback() {
    [[ -r "$ASOUND_DIR/pcm" ]] || return 1
    local line card dev name cardname
    while IFS= read -r line; do
        [[ "$line" == *"playback"* ]] || continue
        card="${line%%-*}"; card="$((10#$card))"
        dev="${line#*-}"; dev="${dev%%:*}"; dev="$((10#$dev))"
        name="${line#*: }"; name="${name%% :*}"
        cardname="$(sed -n "s/^ *$card \[[^]]*\]: [^ ]* - //p" "$ASOUND_DIR/cards" 2>/dev/null | head -1)"
        printf 'hw:%s,%s\t%s — %s\n' "$card" "$dev" "${cardname:-card $card}" "$name"
    done < "$ASOUND_DIR/pcm"
}

# Czy urządzenie hw:C,D jest teraz otwarte przez kogoś (np. pipewire)?
# /proc/asound/cardC/pcmDp/sub0/status = "closed", gdy wolne. Brak pliku =
# nie wiemy (traktuj jak wolne, mpd i tak to zweryfikuje).
alsa_device_busy() {
    local hw="$1" card dev f
    card="${hw#hw:}"; card="${card%%,*}"; dev="${hw##*,}"
    f="$ASOUND_DIR/card$card/pcm${dev}p/sub0/status"
    [[ -r "$f" ]] || return 1
    ! grep -qx 'closed' "$f"
}

# Zapisz output.conf (atomowo) dla trybu pipewire albo alsa <hw:C,D>.
write_mpd_output_conf() {
    local mode="$1" hw="${2:-}" tmp
    mkdir -p "$(dirname "$MPD_OUTPUT_CONF")"
    tmp="$(mktemp "${MPD_OUTPUT_CONF}.XXXXXX")" || { echo -e "  ${RED}✗ mktemp failed.${NC}"; return 1; }
    {
        echo "# generated by archenemy (Super+A → [o]) — wyjście audio mpd (warstwa maszynowa)."
        echo "# pipewire zalecane; alsa = tryb wylaczny (patrz README, sekcja Music stack)."
        echo "audio_output {"
        if [[ "$mode" == "alsa" ]]; then
            echo "    type        \"alsa\""
            echo "    name        \"ALSA $hw\""
            echo "    device      \"$hw\""
            # software: mpd NIE kręci gałką sprzętową pod pipewire — inaczej
            # poziom karty zmieniałby się „sam” po powrocie na pipewire.
            echo "    mixer_type  \"software\""
        else
            echo "    type  \"pipewire\""
            echo "    name  \"PipeWire\""
        fi
        echo "}"
    } > "$tmp"
    mv "$tmp" "$MPD_OUTPUT_CONF"
}

# Restart mpd i czekanie, aż odpowie (do ~5 s). Zwraca 1, gdy nie wstał.
restart_mpd_and_wait() {
    systemctl --user restart mpd.service 2>/dev/null || return 1
    local _i
    for _i in $(seq 1 25); do
        mpc status >/dev/null 2>&1 && return 0
        sleep 0.2
    done
    return 1
}

# Zastosuj tryb: zapis configu + restart + WERYFIKACJA (sekundowy test
# odtwarzania — mpd otwiera wyjście dopiero przy graniu, więc sam restart
# niczego nie dowodzi). Stan odtwarzania sprzed testu jest przywracany.
# Zwraca 0 = działa, 1 = nie działa (wołający robi rollback).
apply_mpd_output() {
    local mode="$1" hw="${2:-}" was_playing=0 err=""
    mpc status 2>/dev/null | grep -q '^\[playing\]' && was_playing=1
    write_mpd_output_conf "$mode" "$hw" || return 1
    if ! restart_mpd_and_wait; then
        echo -e "  ${RED}✗ mpd nie wstał po restarcie (journalctl --user -u mpd).${NC}"
        return 1
    fi
    # Test: pusta kolejka = nie ma czym sprawdzić, zaufaj konfiguracji.
    if [[ -n "$(mpc playlist 2>/dev/null | head -1)" ]]; then
        mpc play >/dev/null 2>&1
        sleep 1
        err="$(mpc status 2>&1 | sed -n 's/^ERROR: //p' | head -1)"
        (( was_playing )) || mpc pause >/dev/null 2>&1
        if [[ -n "$err" ]]; then
            echo -e "  ${RED}✗ mpd: $err${NC}"
            return 1
        fi
    fi
    write_dat "$MPD_OUTPUT_DAT" "$mode${hw:+ $hw}"
    return 0
}

audio_output_menu() {
    if ! command -v mpd >/dev/null 2>&1 || ! command -v mpc >/dev/null 2>&1; then
        echo -e "  ${YELLOW}mpd/mpc not installed — the music stack is optional (install.sh → additional packages).${NC}"
        return
    fi
    local cur="pipewire"
    [[ -f "$MPD_OUTPUT_DAT" ]] && cur="$(<"$MPD_OUTPUT_DAT")"

    echo ""
    echo -e "  mpd audio output: ${CYAN}${cur}${NC}"
    echo -e "    ${BLUE}1${NC}) pipewire  — recommended: mixes with the desktop, volume keys work,"
    echo -e "                  music-reactive wallpapers (♪) hear mpd"
    echo -e "    ${BLUE}2${NC}) alsa      — EXCLUSIVE hw: device (bit-perfect / experiments)"
    echo ""
    echo -e "  ${YELLOW}⚠ ALSA warning:${NC} while mpd holds the sound card, notifications, the browser,"
    echo -e "    volume keys and ♪ wallpapers may lose audio; if PipeWire holds the card, mpd"
    echo -e "    fails to open it. A 1-second test play runs after switching; on failure"
    echo -e "    the output goes back to pipewire automatically. PipeWire itself is never"
    echo -e "    stopped by this menu. mpd restarts (playback resumes paused)."
    echo ""
    local ans; ans="$(read_key "  Choose [1-2, Esc = cancel]: ")"
    case "$ans" in
        1)
            if apply_mpd_output pipewire; then
                echo -e "  ${GREEN}✓ mpd output: pipewire${NC}"
            else
                echo -e "  ${RED}✗ pipewire output failed — check: journalctl --user -u mpd${NC}"
            fi
            ;;
        2)
            local devices=() line
            while IFS= read -r line; do [[ -n "$line" ]] && devices+=("$line"); done < <(list_alsa_playback)
            if [[ ${#devices[@]} -eq 0 ]]; then
                echo -e "  ${RED}✗ No ALSA playback devices found in /proc/asound.${NC}"
                return
            fi
            echo ""
            local i hw busy
            for i in "${!devices[@]}"; do
                hw="${devices[$i]%%$'\t'*}"
                busy=""
                alsa_device_busy "$hw" && busy=" ${YELLOW}(busy — held by PipeWire?)${NC}"
                printf "    ${BLUE}%d${NC}) %-10s %s%b\n" "$((i+1))" "$hw" "${devices[$i]#*$'\t'}" "$busy"
            done
            echo ""
            read -rp "  Device number (Enter = cancel): " ans
            [[ "$ans" =~ ^[0-9]+$ ]] || { echo -e "  ${YELLOW}Cancelled.${NC}"; return; }
            (( ans >= 1 && ans <= ${#devices[@]} )) || { echo -e "  ${RED}✗ Out of range.${NC}"; return; }
            hw="${devices[$((ans-1))]%%$'\t'*}"
            if alsa_device_busy "$hw"; then
                echo -e "  ${YELLOW}⚠ $hw is open right now — mpd will most likely fail to grab it.${NC}"
                local go; go="$(read_key "  Try anyway? [y/N]: ")"
                [[ "$go" =~ ^[Yy]$ ]] || { echo -e "  ${YELLOW}Cancelled.${NC}"; return; }
            fi
            if apply_mpd_output alsa "$hw"; then
                echo -e "  ${GREEN}✓ mpd output: alsa $hw${NC}"
                echo -e "  ${YELLOW}  Back to pipewire any time: Super+A → [o] → 1.${NC}"
            else
                echo -e "  ${YELLOW}↩ Rolling back to pipewire…${NC}"
                if apply_mpd_output pipewire; then
                    echo -e "  ${GREEN}✓ mpd output: pipewire (restored)${NC}"
                    notify-send "archenemy" "mpd: ALSA $hw failed — output restored to pipewire." 2>/dev/null
                else
                    echo -e "  ${RED}✗ Rollback failed too — check: journalctl --user -u mpd${NC}"
                    notify-send -u critical "archenemy" "mpd: ALSA failed and pipewire rollback failed — see journalctl --user -u mpd" 2>/dev/null
                fi
            fi
            ;;
        ""|$'\e') echo -e "  ${YELLOW}Cancelled.${NC}" ;;
        *)  echo -e "  ${RED}✗ Pick 1 or 2.${NC}" ;;
    esac
}

# ─── TIMER (waybar) ──────────────────────────────────────────────────────────

# Ustawienia modułu custom/timer: włączenie na pasku, domyślny czas odliczania
# i kolor tekstu. Pliki data/timer-*.dat czyta scripts/waybar/timer.sh; po
# każdej zmianie leci sygnał 11 = pasek przerysowuje się od razu.
# Sam bieg timera (start/pauza/reset) obsługuje pasek, nie to menu.
timer_menu() {
    local lib="$ARCHENEMY_DIR/scripts/waybar/lib/timer-state.sh"
    if [[ ! -f "$lib" ]]; then
        echo -e "  ${RED}✗ Missing ${lib} — run ./install/install.sh once.${NC}"
        return
    fi
    # shellcheck source=/dev/null
    source "$lib"

    local enabled_label="off"
    timer_enabled && enabled_label="on"
    timer_load_state

    echo ""
    echo -e "  Timer (waybar): ${CYAN}${enabled_label}${NC} · ${CYAN}$(timer_duration_minutes) min${NC} · ${CYAN}$(timer_color)${NC} · now: ${CYAN}${TIMER_STATUS}${NC}"
    if [[ "$enabled_label" == "on" ]]; then
        echo -e "    ${BLUE}1${NC}) turn off"
    else
        echo -e "    ${BLUE}1${NC}) turn on"
    fi
    echo -e "    ${BLUE}2${NC}) default duration (minutes)"
    echo -e "    ${BLUE}3${NC}) text colour (hex)"
    echo ""
    local ans; ans="$(read_key "  Choose [1-3, Esc = cancel]: ")"

    case "$ans" in
        1)
            local target="1"
            [[ "$enabled_label" == "on" ]] && target="0"
            write_dat "$TIMER_ENABLED_DAT" "$target" || return
            if [[ "$target" == "1" ]]; then
                echo -e "  ${GREEN}✓ Timer shown on the bar.${NC}"
            else
                echo -e "  ${GREEN}✓ Timer hidden (the clock goes back to the exact centre).${NC}"
            fi
            ;;
        2)
            local mins
            read -rp "  Default duration in minutes [1-${TIMER_MAX_MINUTES}]: " mins
            mins=$(trim "$mins")
            if [[ ! "$mins" =~ ^[0-9]+$ ]] || (( mins < 1 || mins > TIMER_MAX_MINUTES )); then
                echo -e "  ${RED}✗ '${mins}' is not a number between 1 and ${TIMER_MAX_MINUTES}.${NC}"
                return
            fi
            write_dat "$TIMER_DURATION_DAT" "$mins" || return
            # Nowy czas ma być widoczny od razu — ale tylko wtedy, gdy nie
            # przerwie trwającego odliczania (reset zabiłby bieg w połowie).
            if [[ "$TIMER_STATUS" == "running" ]]; then
                echo -e "  ${YELLOW}⚠ Timer is running — the new default applies after a reset (RMB on the bar).${NC}"
            else
                bash "$ARCHENEMY_DIR/scripts/waybar/timer-ctl.sh" reset
            fi
            echo -e "  ${GREEN}✓ Default duration: ${mins} min${NC}"
            ;;
        3)
            local hex
            read -rp "  Text colour as hex (e.g. #ff0000): " hex
            hex=$(trim "$hex")
            [[ "$hex" == "#"* ]] || hex="#$hex"
            if [[ ! "$hex" =~ ^#[0-9a-fA-F]{6}$ ]]; then
                echo -e "  ${RED}✗ '${hex}' is not a #rrggbb colour.${NC}"
                return
            fi
            write_dat "$TIMER_COLOR_DAT" "$hex" || return
            echo -e "  ${GREEN}✓ Timer colour: ${hex}${NC}"
            ;;
        ""|$'\e') echo -e "  ${YELLOW}Cancelled.${NC}"; return ;;
        *)  echo -e "  ${RED}✗ Pick 1, 2 or 3.${NC}"; return ;;
    esac

    pkill -RTMIN+11 waybar 2>/dev/null
}

# ─── PĘTLA GŁÓWNA ─────────────────────────────────────────────────────────────

ensure_conf

while :; do
    clear
    echo -e "${BLUE}"
    echo "  ┌─────────────────────────────────────┐"
    echo "  │      archenemy · app shortcuts      │"
    echo "  └─────────────────────────────────────┘"
    echo -e "${NC}"
    echo -e "  Your binds (Super + key):"
    echo ""
    list_binds
    echo ""
    echo -e "  ${GREEN}[a]${NC} add bind   ${RED}[d]${NC} remove bind   ${BLUE}[s]${NC} all shortcuts   ${YELLOW}[w]${NC} workspace mode   ${GREEN}[v]${NC} volume bar   ${GREEN}[t]${NC} timer   ${GREEN}[u]${NC} autostart apps   ${GREEN}[o]${NC} mpd audio output   ${GREEN}[p]${NC} update archenemy   ${CYAN}[q]${NC} quit (Esc also quits)"
    echo ""
    choice="$(read_key "  Choice: ")"

    case "$choice" in
        a|A) add_bind ;;
        d|D) remove_bind ;;
        s|S) show_all_binds; continue ;;
        w|W) workspace_mode_menu ;;
        v|V) volume_style_menu ;;
        t|T) timer_menu ;;
        u|U) bash "$ARCHENEMY_DIR/scripts/appbinds/autostart-picker.sh"; continue ;;
        o|O) audio_output_menu ;;
        p|P) bash "$ARCHENEMY_DIR/scripts/appbinds/update-archenemy.sh"; continue ;;
        q|Q|$'\e') exit 0 ;;
        *)   continue ;;
    esac

    echo ""
    read -rp "  Press Enter to continue..." _
done
