#!/bin/bash

# =============================================
#   archenemy - appbinds.sh
#   Terminalowy menedżer skrótów do aplikacji (Super + klawisz).
#   Otwierany przez Super+A (pływające okno alacritty).
#   UI po angielsku (decyzja właściciela 2026-07-12).
#
#   Bindy lądują w warstwie OSOBISTEJ (poza gitem):
#   ~/archenemy/config/hypr/appbinds.lua
#   — hyprland.lua rice'a require'uje ten plik.
# =============================================

ARCHENEMY_DIR="$HOME/archenemy"
BINDS_CONF="$ARCHENEMY_DIR/config/hypr/appbinds.lua"
CONFIG_DIR="$HOME/.config"

# Pliki, w których klawisz może już być zajęty (bindy Super+klawisz archenemy).
# workspaces-monitors.lua: od 2026-07-17 bindy Super+1..0 są GENEROWANE tam
# (zależą od trybu shared/decades) — bez tego wpisu TUI pozwoliłoby przykryć
# nawigację workspace'ów własnym bindem.
CONFLICT_FILES=(
    "$CONFIG_DIR/hypr/hyprland.lua"
    "$ARCHENEMY_DIR/config/hypr/workspaces.lua"
    "$ARCHENEMY_DIR/config/hypr/workspaces-monitors.lua"
    "$BINDS_CONF"
)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Czysty bashowy trim — NIE `| xargs`: xargs robi przetwarzanie cudzysłowów,
# więc `sh -c 'btop; read'` gubił apostrofy, a samotny apostrof wysypywał
# cały pipe („unmatched single quote" → „Empty command").
trim() {
    local s="$1"
    s="${s#"${s%%[![:space:]]*}"}"
    s="${s%"${s##*[![:space:]]}"}"
    printf '%s' "$s"
}

# Jeden klawisz bez Enter (menu/potwierdzenia — nie wolne wpisywanie tekstu).
# Zwraca $'\e' dla samego Escape, żeby wołający mógł potraktować go jak
# anulowanie/wyjście.
read_key() {
    local prompt="$1" key=""
    IFS= read -rsn1 -p "$prompt" key
    echo "" >&2
    printf '%s' "$key"
}

# ─── PLIK BINDÓW ──────────────────────────────────────────────────────────────

# Upewnij się, że plik istnieje (install.sh go tworzy, ale nie zakładaj)
ensure_conf() {
    [[ -f "$BINDS_CONF" ]] && return
    mkdir -p "$(dirname "$BINDS_CONF")"
    # local mainMod jest konieczny: require() = osobny scope Lua, plik nie
    # widzi zmiennych z hyprland.lua rice'a.
    {
        echo "-- generated by archenemy install.sh"
        echo "-- Your app shortcuts — edit via Super+A (scripts/appbinds/appbinds.sh)."
        echo "local mainMod = \"SUPER\""
    } > "$BINDS_CONF"
}

# Czy klawisz jest już zajęty przez jakikolwiek bind Super+klawisz?
# (bez dodatkowych modyfikatorów — SUPER SHIFT itd. nie koliduje)
key_taken() {
    local key="$1"
    # Dwa warianty emisji: `hl.bind(mainMod .. " + KEY", ...` (configi archenemy)
    # oraz `hl.bind("SUPER + KEY", ...` (gdyby ktoś wpisał moda dosłownie).
    grep -hqiE "^hl\\.bind\\((mainMod[[:space:]]*\\.\\.[[:space:]]*\" \\+ ${key}\"|\"SUPER \\+ ${key}\")," \
        "${CONFLICT_FILES[@]}" 2>/dev/null
}

# Wypisz obecne bindy użytkownika, ponumerowane
list_binds() {
    local i=0 key cmd
    while IFS= read -r line; do
        # hl.bind(mainMod .. " + KEY", hl.dsp.exec_cmd("CMD"))
        [[ "$line" =~ ^hl\.bind\(mainMod[[:space:]]*\.\.[[:space:]]*\"\ \+\ ([A-Za-z0-9_]+)\",[[:space:]]*hl\.dsp\.exec_cmd\(\"(.*)\"\)\) ]] || continue
        i=$((i + 1))
        key="${BASH_REMATCH[1]}"
        cmd="${BASH_REMATCH[2]}"
        printf "    ${CYAN}%2d)${NC} Super + ${BLUE}%-12s${NC} → %s\n" "$i" "$key" "$cmd"
    done < "$BINDS_CONF"
    if [[ $i -eq 0 ]]; then
        echo -e "    ${YELLOW}(no custom binds yet — add your first!)${NC}"
    fi
    return 0
}

# Przeładuj Hyprlanda, żeby bind działał od razu
reload_hyprland() {
    if command -v hyprctl &>/dev/null; then
        hyprctl reload &>/dev/null
        echo -e "  ${GREEN}✓ Hyprland reloaded — the bind works immediately.${NC}"
    else
        echo -e "  ${YELLOW}⚠ hyprctl unavailable — reload Hyprland manually.${NC}"
    fi
}

# ─── PODGLĄD WSZYSTKICH SKRÓTÓW ──────────────────────────────────────────────

# Ładna nazwa klawisza (mysz, scroll) — reszta zostaje jak w configu
pretty_key() {
    case "$1" in
        mouse:272)  echo "LMB" ;;
        mouse:273)  echo "RMB" ;;
        mouse_down) echo "scroll ↓" ;;
        mouse_up)   echo "scroll ↑" ;;
        *)          echo "$1" ;;
    esac
}

# Wypisz bindy z jednego pliku configu Lua, po jednej linii.
# Konwencja repo: JEDEN bind = JEDNA linia `hl.bind(...)`. Komentarzy --
# nie ucinamy na ślepo (komendy zawierają "--", np. --clipboard-only) —
# strukturę wyciąga regex, ogon linii jest ignorowany.
print_binds_from() {
    local file="$1"
    [[ -f "$file" ]] || return 0
    local line keys rest combo action var

    while IFS= read -r line; do
        # 1. argument hl.bind: mainMod .. " + KEY" albo dosłowny "KEYS"
        if [[ "$line" =~ ^hl\.bind\(mainMod[[:space:]]*\.\.[[:space:]]*\"([^\"]*)\",[[:space:]]*(.*)$ ]]; then
            keys="SUPER${BASH_REMATCH[1]}"
            rest="${BASH_REMATCH[2]}"
        elif [[ "$line" =~ ^hl\.bind\(\"([^\"]*)\",[[:space:]]*(.*)$ ]]; then
            keys="${BASH_REMATCH[1]}"
            rest="${BASH_REMATCH[2]}"
        else
            continue
        fi

        # "SUPER + SHIFT + F" → "Super+SHIFT+F"; myszy/scroll przez pretty_key
        combo="${keys// + /+}"
        combo="${combo/#SUPER/Super}"
        combo="${combo/mouse:272/$(pretty_key mouse:272)}"
        combo="${combo/mouse:273/$(pretty_key mouse:273)}"
        combo="${combo/mouse_down/$(pretty_key mouse_down)}"
        combo="${combo/mouse_up/$(pretty_key mouse_up)}"

        # exec_cmd("...") → pokaż polecenie; exec_cmd(zmienna) → rozwiń z
        # hyprland.lua; inne dyspozytory → pokaż wywołanie hl.dsp bez opcji bindu
        if [[ "$rest" =~ ^hl\.dsp\.exec_cmd\(\"([^\"]*)\"\) ]]; then
            action="${BASH_REMATCH[1]}"
        elif [[ "$rest" =~ ^hl\.dsp\.exec_cmd\(([A-Za-z_][A-Za-z0-9_]*)\) ]]; then
            var="${BASH_REMATCH[1]}"
            action="${HYPR_VARS[$var]:-\$$var}"
        else
            action="${rest#hl.dsp.}"
            action="${action%, \{*}"        # utnij opcje bindu ({ repeating = ... })
            action="${action%% -- *}"        # utnij komentarz Lua za bindem
            [[ "$action" == *"))" ]] && action="${action%)}"  # domykający nawias hl.bind
        fi

        printf "    %-24s %s\n" "$combo" "$action"
    done < "$file"
}

# Pełna lista: rice + warstwy wspólne/maszynowe/osobiste, przez pager
show_all_binds() {
    # Definicje zmiennych (local terminal = "alacritty" itd.) z aktywnego
    # hyprland.lua rice'a.
    declare -gA HYPR_VARS=()
    local line
    # Guard [[ -f ]]: przed pierwszym przełączeniem rice'a hyprland.lua bywa
    # wiszącym symlinkiem — redirect z niego wysypałby całe [s].
    if [[ -f "$CONFIG_DIR/hypr/hyprland.lua" ]]; then
        while IFS= read -r line; do
            if [[ "$line" =~ ^local[[:space:]]+([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=[[:space:]]*\"(.*)\" ]]; then
                HYPR_VARS[${BASH_REMATCH[1]}]="${BASH_REMATCH[2]}"
            fi
        done < "$CONFIG_DIR/hypr/hyprland.lua"
    fi

    {
        echo -e "${BLUE}  All archenemy shortcuts${NC}  (q = back)"
        echo ""
        echo -e "${CYAN}  ── Rice (hyprland.lua) ──${NC}"
        print_binds_from "$CONFIG_DIR/hypr/hyprland.lua"
        echo ""
        echo -e "${CYAN}  ── Workspaces ──${NC}"
        # Bindy workspace'ów są generowane per tryb (shared/decades) do pliku
        # maszynowego; tracked workspaces.lua trzyma już tylko autostart guarda.
        print_binds_from "$ARCHENEMY_DIR/config/hypr/workspaces-monitors.lua"
        echo ""
        echo -e "${CYAN}  ── Multimedia ──${NC}"
        print_binds_from "$ARCHENEMY_DIR/config/hypr/keyboard.lua"
        echo ""
        echo -e "${CYAN}  ── Hardware (this machine) ──${NC}"
        print_binds_from "$ARCHENEMY_DIR/config/hypr/hardware-keys.lua"
        echo ""
        echo -e "${CYAN}  ── Your binds (Super+A) ──${NC}"
        print_binds_from "$BINDS_CONF"
    } | { command -v less &>/dev/null && less -R || cat; }
}

# ─── AKCJE ────────────────────────────────────────────────────────────────────

add_bind() {
    echo ""
    read -rp "  Key (e.g. g, F5, semicolon, minus): " key
    key=$(trim "$key")

    if [[ -z "$key" ]]; then
        echo -e "  ${YELLOW}⚠ Empty key — cancelled.${NC}"
        return
    fi
    # Nazwa keysym Hyprlanda: litera/cyfra albo nazwa bez spacji i przecinków
    if [[ ! "$key" =~ ^[A-Za-z0-9_]+$ ]]; then
        echo -e "  ${RED}✗ '${key}' does not look like a key name (no spaces or commas).${NC}"
        return
    fi
    # Klawisze-modyfikatory dokładają własny mod do maski w chwili naciśnięcia,
    # więc prosty bind Super+<modyfikator> nigdy nie odpali (wiki: Binding modkeys
    # only) — odrzucamy, zamiast pozwolić na martwy bind.
    if [[ "$key" =~ ^(Shift|Control|Alt|Super|Meta|Hyper)_(L|R)$ ]]; then
        echo -e "  ${RED}✗ '${key}' is a modifier key — a plain Super+${key} bind would never fire.${NC}"
        return
    fi
    if key_taken "$key"; then
        echo -e "  ${RED}✗ Super+${key} is already taken (by archenemy or one of your binds).${NC}"
        return
    fi

    read -rp "  Command (e.g. spotify, steam, alacritty -e btop): " cmd
    cmd=$(trim "$cmd")
    if [[ -z "$cmd" ]]; then
        echo -e "  ${YELLOW}⚠ Empty command — cancelled.${NC}"
        return
    fi
    # Komenda ląduje w stringu Lua — cudzysłów/backslash rozbiłyby składnię pliku.
    if [[ "$cmd" == *'"'* || "$cmd" == *'\'* ]]; then
        echo -e "  ${RED}✗ Command must not contain \" or \\ (it is written into a Lua string).${NC}"
        return
    fi

    # Ostrzeż, jeśli program nie jest zainstalowany (bind i tak można dodać)
    local bin="${cmd%% *}"
    if ! command -v "$bin" &>/dev/null; then
        echo -e "  ${YELLOW}⚠ '${bin}' not found in PATH.${NC}"
        read -rp "  Add anyway? [y/N]: " ans
        [[ "$ans" =~ ^[Yy]$ ]] || return
    fi

    echo "hl.bind(mainMod .. \" + $key\", hl.dsp.exec_cmd(\"$cmd\"))" >> "$BINDS_CONF"
    echo -e "  ${GREEN}✓ Added: Super+${key} → ${cmd}${NC}"
    reload_hyprland
}

remove_bind() {
    # Zbierz numery linii z bindami, w kolejności wyświetlania
    mapfile -t BIND_LINES < <(grep -n '^hl\.bind(' "$BINDS_CONF" | cut -d: -f1)
    if [[ ${#BIND_LINES[@]} -eq 0 ]]; then
        echo -e "  ${YELLOW}⚠ Nothing to remove.${NC}"
        return
    fi

    echo ""
    read -rp "  Bind number to remove (Enter = cancel): " num
    [[ -z "$num" ]] && return
    if [[ ! "$num" =~ ^[0-9]+$ ]] || (( num < 1 || num > ${#BIND_LINES[@]} )); then
        echo -e "  ${RED}✗ There is no bind number '${num}'.${NC}"
        return
    fi

    sed -i "${BIND_LINES[$((num - 1))]}d" "$BINDS_CONF"
    echo -e "  ${GREEN}✓ Removed.${NC}"
    reload_hyprland
}

# ─── TRYB WORKSPACE'ÓW (shared/decades) ──────────────────────────────────────

# Przełączenie trybu na żywo (bez ponownego install.sh). Cała robota —
# regeneracja workspaces-monitors.lua, reload, guard — siedzi w
# scripts/hypr/workspace-mode-switch.sh (jedno źródło prawdy z install.sh).
workspace_mode_menu() {
    local mode_dat="$ARCHENEMY_DIR/data/workspace-mode.dat"
    local switch="$ARCHENEMY_DIR/scripts/hypr/workspace-mode-switch.sh"
    local cur="decades"
    [[ -f "$mode_dat" ]] && cur="$(<"$mode_dat")"
    local other="shared"; [[ "$cur" == "shared" ]] && other="decades"

    echo ""
    echo -e "  Current workspace mode: ${CYAN}${cur}${NC}"
    echo -e "    ${BLUE}shared${NC}  — 10 global workspaces (1-10) shared by all monitors"
    echo -e "    ${BLUE}decades${NC} — each monitor gets its own 1-10 (isolated decades)"
    echo ""
    local ans; ans="$(read_key "  Switch to '${other}'? [y/N]: ")"
    [[ "$ans" =~ ^[Yy]$ ]] || { echo -e "  ${YELLOW}Cancelled.${NC}"; return; }

    if [[ ! -x "$switch" ]]; then
        echo -e "  ${RED}✗ Missing ${switch} — run ./install/install.sh once.${NC}"
        return
    fi
    bash "$switch" "$other"
}

# ─── STYL PASKA GŁOŚNOŚCI (waybar) ───────────────────────────────────────────

# Wybór stylu paska custom/volumebar (segments/blocks). Zapis do
# data/volume-bar-style.dat (czyta go scripts/waybar/volume-bar.sh), potem
# sygnał 10 do waybara = pasek przerysowuje się od razu.
volume_style_menu() {
    local style_dat="$ARCHENEMY_DIR/data/volume-bar-style.dat"
    local cur="segments"
    [[ -f "$style_dat" ]] && cur="$(<"$style_dat")"

    echo ""
    echo -e "  Volume bar style (waybar): ${CYAN}${cur}${NC}"
    echo -e "    ${BLUE}1${NC}) segments   ▮▮▮▮▮▮▯▯▯▯"
    echo -e "    ${BLUE}2${NC}) blocks     ██████░░░░"
    echo ""
    local ans; ans="$(read_key "  Choose [1-2, Esc = cancel]: ")"
    local target=""
    case "$ans" in
        1) target="segments" ;;
        2) target="blocks" ;;
        ""|$'\e') echo -e "  ${YELLOW}Cancelled.${NC}"; return ;;
        *)  echo -e "  ${RED}✗ Pick 1 or 2.${NC}"; return ;;
    esac

    mkdir -p "$(dirname "$style_dat")"
    local tmp
    tmp="$(mktemp "${style_dat}.XXXXXX")" || { echo -e "  ${RED}✗ mktemp failed.${NC}"; return; }
    printf '%s\n' "$target" > "$tmp"
    mv "$tmp" "$style_dat"
    pkill -RTMIN+10 waybar 2>/dev/null
    echo -e "  ${GREEN}✓ Volume bar style: ${target}${NC}"
}

# ─── PĘTLA GŁÓWNA ─────────────────────────────────────────────────────────────

ensure_conf

while :; do
    clear
    echo -e "${BLUE}"
    echo "  ┌─────────────────────────────────────┐"
    echo "  │      archenemy · app shortcuts      │"
    echo "  └─────────────────────────────────────┘"
    echo -e "${NC}"
    echo -e "  Your binds (Super + key):"
    echo ""
    list_binds
    echo ""
    echo -e "  ${GREEN}[a]${NC} add bind   ${RED}[d]${NC} remove bind   ${BLUE}[s]${NC} all shortcuts   ${YELLOW}[w]${NC} workspace mode   ${GREEN}[v]${NC} volume bar   ${GREEN}[u]${NC} autostart apps   ${GREEN}[p]${NC} update archenemy   ${CYAN}[q]${NC} quit (Esc also quits)"
    echo ""
    choice="$(read_key "  Choice: ")"

    case "$choice" in
        a|A) add_bind ;;
        d|D) remove_bind ;;
        s|S) show_all_binds; continue ;;
        w|W) workspace_mode_menu ;;
        v|V) volume_style_menu ;;
        u|U) bash "$ARCHENEMY_DIR/scripts/appbinds/autostart-picker.sh"; continue ;;
        p|P) bash "$ARCHENEMY_DIR/scripts/appbinds/update-archenemy.sh"; continue ;;
        q|Q|$'\e') exit 0 ;;
        *)   continue ;;
    esac

    echo ""
    read -rp "  Press Enter to continue..." _
done
