#!/bin/bash

# =============================================
#   archenemy - appbinds.sh
#   Terminalowy menedżer skrótów do aplikacji (Super + klawisz).
#   Otwierany przez Super+A (pływające okno alacritty).
#   UI po angielsku (decyzja właściciela 2026-07-12).
#
#   Bindy lądują w warstwie OSOBISTEJ (poza gitem):
#   ~/archenemy/config/hypr/appbinds.conf
#   — hyprland.conf rice'a source'uje ten plik.
# =============================================

ARCHENEMY_DIR="$HOME/archenemy"
BINDS_CONF="$ARCHENEMY_DIR/config/hypr/appbinds.conf"
CONFIG_DIR="$HOME/.config"

# Pliki, w których klawisz może już być zajęty (bindy Super+klawisz archenemy).
# workspaces-monitors.conf: od 2026-07-17 bindy Super+1..0 są GENEROWANE tam
# (zależą od trybu shared/decades) — bez tego wpisu TUI pozwoliłoby przykryć
# nawigację workspace'ów własnym bindem.
CONFLICT_FILES=(
    "$CONFIG_DIR/hypr/hyprland.conf"
    "$ARCHENEMY_DIR/config/hypr/workspaces.conf"
    "$ARCHENEMY_DIR/config/hypr/workspaces-monitors.conf"
    "$BINDS_CONF"
)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Czysty bashowy trim — NIE `| xargs`: xargs robi przetwarzanie cudzysłowów,
# więc `sh -c 'btop; read'` gubił apostrofy, a samotny apostrof wysypywał
# cały pipe („unmatched single quote" → „Empty command").
trim() {
    local s="$1"
    s="${s#"${s%%[![:space:]]*}"}"
    s="${s%"${s##*[![:space:]]}"}"
    printf '%s' "$s"
}

# ─── PLIK BINDÓW ──────────────────────────────────────────────────────────────

# Upewnij się, że plik istnieje (install.sh go tworzy, ale nie zakładaj)
ensure_conf() {
    [[ -f "$BINDS_CONF" ]] && return
    mkdir -p "$(dirname "$BINDS_CONF")"
    {
        echo "# generated by archenemy install.sh"
        echo "# Your app shortcuts — edit via Super+A (scripts/appbinds/appbinds.sh)."
    } > "$BINDS_CONF"
}

# Czy klawisz jest już zajęty przez jakikolwiek bind Super+klawisz?
# (bez dodatkowych modyfikatorów — SUPER SHIFT itd. nie koliduje)
key_taken() {
    local key="$1"
    grep -hqiE "^bind[a-z]*[[:space:]]*=[[:space:]]*\\\$mainMod[[:space:]]*,[[:space:]]*${key}[[:space:]]*," \
        "${CONFLICT_FILES[@]}" 2>/dev/null
}

# Wypisz obecne bindy użytkownika, ponumerowane
list_binds() {
    local i=0 key cmd
    while IFS= read -r line; do
        [[ "$line" =~ ^bind ]] || continue
        i=$((i + 1))
        # bind = $mainMod, KEY, exec, CMD
        key=$(trim "$(cut -d, -f2 <<<"$line")")
        cmd=$(trim "$(cut -d, -f4- <<<"$line")")
        printf "    ${CYAN}%2d)${NC} Super + ${BLUE}%-12s${NC} → %s\n" "$i" "$key" "$cmd"
    done < "$BINDS_CONF"
    if [[ $i -eq 0 ]]; then
        echo -e "    ${YELLOW}(no custom binds yet — add your first!)${NC}"
    fi
    return 0
}

# Przeładuj Hyprlanda, żeby bind działał od razu
reload_hyprland() {
    if command -v hyprctl &>/dev/null; then
        hyprctl reload &>/dev/null
        echo -e "  ${GREEN}✓ Hyprland reloaded — the bind works immediately.${NC}"
    else
        echo -e "  ${YELLOW}⚠ hyprctl unavailable — reload Hyprland manually.${NC}"
    fi
}

# ─── PODGLĄD WSZYSTKICH SKRÓTÓW ──────────────────────────────────────────────

# Ładna nazwa klawisza (mysz, scroll) — reszta zostaje jak w configu
pretty_key() {
    case "$1" in
        mouse:272)  echo "LMB" ;;
        mouse:273)  echo "RMB" ;;
        mouse_down) echo "scroll ↓" ;;
        mouse_up)   echo "scroll ↑" ;;
        *)          echo "$1" ;;
    esac
}

# Wypisz bindy z jednego pliku configu (bind/binde/bindm), po jednej linii
print_binds_from() {
    local file="$1"
    [[ -f "$file" ]] || return 0
    local line rest mods key dispatcher args combo action var

    while IFS= read -r line; do
        line="${line%%#*}"
        [[ "$line" =~ ^bind[a-z]*[[:space:]]*=(.*)$ ]] || continue
        rest="${BASH_REMATCH[1]}"
        IFS=',' read -r mods key dispatcher args <<< "$rest"
        mods=$(trim "$mods")
        key=$(pretty_key "$(trim "$key")")
        dispatcher=$(trim "$dispatcher")
        args=$(trim "$args")

        # $mainMod → Super, 'SUPER SHIFT' → 'Super+Shift'
        mods="${mods//\$mainMod/Super}"
        mods=$(echo "$mods" | tr -s ' ' '+')
        combo="${mods:+$mods+}$key"

        # exec → pokaż polecenie (rozwiń zmienną $nazwa z hyprland.conf),
        # inne dyspozytory → pokaż akcję Hyprlanda
        if [[ "$dispatcher" == "exec" ]]; then
            if [[ "$args" =~ ^\$([A-Za-z_][A-Za-z0-9_]*)$ ]]; then
                var="${BASH_REMATCH[1]}"
                [[ -n "${HYPR_VARS[$var]:-}" ]] && args="${HYPR_VARS[$var]}"
            fi
            action="$args"
        else
            action="$dispatcher${args:+ $args}"
        fi

        printf "    %-24s %s\n" "$combo" "$action"
    done < "$file"
}

# Pełna lista: rice + warstwy wspólne/maszynowe/osobiste, przez pager
show_all_binds() {
    # Definicje zmiennych ($terminal = alacritty itd.) z aktywnego hyprland.conf
    declare -gA HYPR_VARS=()
    local line
    # Guard [[ -f ]]: przed pierwszym przełączeniem rice'a hyprland.conf bywa
    # wiszącym symlinkiem — redirect z niego wysypałby całe [s].
    if [[ -f "$CONFIG_DIR/hypr/hyprland.conf" ]]; then
        while IFS= read -r line; do
            if [[ "$line" =~ ^\$([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=[[:space:]]*(.+)$ ]]; then
                HYPR_VARS[${BASH_REMATCH[1]}]=$(trim "${BASH_REMATCH[2]}")
            fi
        done < "$CONFIG_DIR/hypr/hyprland.conf"
    fi

    {
        echo -e "${BLUE}  All archenemy shortcuts${NC}  (q = back)"
        echo ""
        echo -e "${CYAN}  ── Rice (hyprland.conf) ──${NC}"
        print_binds_from "$CONFIG_DIR/hypr/hyprland.conf"
        echo ""
        echo -e "${CYAN}  ── Workspaces ──${NC}"
        # Bindy workspace'ów są generowane per tryb (shared/decades) do pliku
        # maszynowego; tracked workspaces.conf trzyma już tylko exec-once guarda.
        print_binds_from "$ARCHENEMY_DIR/config/hypr/workspaces-monitors.conf"
        echo ""
        echo -e "${CYAN}  ── Multimedia ──${NC}"
        print_binds_from "$ARCHENEMY_DIR/config/hypr/keyboard.conf"
        echo ""
        echo -e "${CYAN}  ── Hardware (this machine) ──${NC}"
        print_binds_from "$ARCHENEMY_DIR/config/hypr/hardware-keys.conf"
        echo ""
        echo -e "${CYAN}  ── Your binds (Super+A) ──${NC}"
        print_binds_from "$BINDS_CONF"
    } | { command -v less &>/dev/null && less -R || cat; }
}

# ─── AKCJE ────────────────────────────────────────────────────────────────────

add_bind() {
    echo ""
    read -rp "  Key (e.g. g, F5, semicolon, minus): " key
    key=$(trim "$key")

    if [[ -z "$key" ]]; then
        echo -e "  ${YELLOW}⚠ Empty key — cancelled.${NC}"
        return
    fi
    # Nazwa keysym Hyprlanda: litera/cyfra albo nazwa bez spacji i przecinków
    if [[ ! "$key" =~ ^[A-Za-z0-9_]+$ ]]; then
        echo -e "  ${RED}✗ '${key}' does not look like a key name (no spaces or commas).${NC}"
        return
    fi
    if key_taken "$key"; then
        echo -e "  ${RED}✗ Super+${key} is already taken (by archenemy or one of your binds).${NC}"
        return
    fi

    read -rp "  Command (e.g. spotify, steam, alacritty -e btop): " cmd
    cmd=$(trim "$cmd")
    if [[ -z "$cmd" ]]; then
        echo -e "  ${YELLOW}⚠ Empty command — cancelled.${NC}"
        return
    fi

    # Ostrzeż, jeśli program nie jest zainstalowany (bind i tak można dodać)
    local bin="${cmd%% *}"
    if ! command -v "$bin" &>/dev/null; then
        echo -e "  ${YELLOW}⚠ '${bin}' not found in PATH.${NC}"
        read -rp "  Add anyway? [y/N]: " ans
        [[ "$ans" =~ ^[Yy]$ ]] || return
    fi

    echo "bind = \$mainMod, $key, exec, $cmd" >> "$BINDS_CONF"
    echo -e "  ${GREEN}✓ Added: Super+${key} → ${cmd}${NC}"
    reload_hyprland
}

remove_bind() {
    # Zbierz numery linii z bindami, w kolejności wyświetlania
    mapfile -t BIND_LINES < <(grep -n '^bind' "$BINDS_CONF" | cut -d: -f1)
    if [[ ${#BIND_LINES[@]} -eq 0 ]]; then
        echo -e "  ${YELLOW}⚠ Nothing to remove.${NC}"
        return
    fi

    echo ""
    read -rp "  Bind number to remove (Enter = cancel): " num
    [[ -z "$num" ]] && return
    if [[ ! "$num" =~ ^[0-9]+$ ]] || (( num < 1 || num > ${#BIND_LINES[@]} )); then
        echo -e "  ${RED}✗ There is no bind number '${num}'.${NC}"
        return
    fi

    sed -i "${BIND_LINES[$((num - 1))]}d" "$BINDS_CONF"
    echo -e "  ${GREEN}✓ Removed.${NC}"
    reload_hyprland
}

# ─── TRYB WORKSPACE'ÓW (shared/decades) ──────────────────────────────────────

# Przełączenie trybu na żywo (bez ponownego install.sh). Cała robota —
# regeneracja workspaces-monitors.conf, reload, guard — siedzi w
# scripts/hypr/workspace-mode-switch.sh (jedno źródło prawdy z install.sh).
workspace_mode_menu() {
    local mode_dat="$ARCHENEMY_DIR/data/workspace-mode.dat"
    local switch="$ARCHENEMY_DIR/scripts/hypr/workspace-mode-switch.sh"
    local cur="decades"
    [[ -f "$mode_dat" ]] && cur="$(<"$mode_dat")"
    local other="shared"; [[ "$cur" == "shared" ]] && other="decades"

    echo ""
    echo -e "  Current workspace mode: ${CYAN}${cur}${NC}"
    echo -e "    ${BLUE}shared${NC}  — 10 global workspaces (1-10) shared by all monitors"
    echo -e "    ${BLUE}decades${NC} — each monitor gets its own 1-10 (isolated decades)"
    echo ""
    read -rp "  Switch to '${other}'? [y/N]: " ans
    [[ "$ans" =~ ^[Yy]$ ]] || { echo -e "  ${YELLOW}Cancelled.${NC}"; return; }

    if [[ ! -x "$switch" ]]; then
        echo -e "  ${RED}✗ Missing ${switch} — run ./install/install.sh once.${NC}"
        return
    fi
    bash "$switch" "$other"
}

# ─── PĘTLA GŁÓWNA ─────────────────────────────────────────────────────────────

ensure_conf

while :; do
    clear
    echo -e "${BLUE}"
    echo "  ┌─────────────────────────────────────┐"
    echo "  │      archenemy · app shortcuts      │"
    echo "  └─────────────────────────────────────┘"
    echo -e "${NC}"
    echo -e "  Your binds (Super + key):"
    echo ""
    list_binds
    echo ""
    echo -e "  ${GREEN}[a]${NC} add bind   ${RED}[d]${NC} remove bind   ${BLUE}[s]${NC} all shortcuts   ${YELLOW}[w]${NC} workspace mode   ${CYAN}[q]${NC} quit"
    echo ""
    read -rp "  Choice: " choice

    case "$choice" in
        a|A) add_bind ;;
        d|D) remove_bind ;;
        s|S) show_all_binds; continue ;;
        w|W) workspace_mode_menu ;;
        q|Q) exit 0 ;;
        *)   ;;
    esac

    echo ""
    read -rp "  Press Enter to continue..." _
done
