#!/bin/bash

# =============================================
#   archenemy - lib/timer-state.sh
#   Wspólna warstwa danych timera waybara (moduł custom/timer).
#   Source'ują to: scripts/waybar/timer.sh (render) i timer-ctl.sh (klikanie).
#   Biblioteka — NIE uruchamiaj bezpośrednio.
#
#   Cztery pliki warstwy MASZYNOWEJ (data/, poza gitem):
#     timer-enabled.dat   1/0        — czy moduł ma się w ogóle pokazać
#     timer-duration.dat  1..999     — domyślne odliczanie w minutach
#     timer-color.dat     #rrggbb    — kolor tekstu (pango span, nie CSS)
#     timer-state.dat     key=value  — stan biegu (status/remaining/end/notified)
#
#   KAŻDY odczyt ma fallback: pliki pisze TUI (Super+A → [t]) i install.sh [8k],
#   ale człowiek też może je edytować ręcznie — nierozpoznana wartość nigdy nie
#   wywala modułu, tylko wraca do domyślnej.
# =============================================

TIMER_DATA_DIR="${TIMER_DATA_DIR:-$HOME/archenemy/data}"
TIMER_ENABLED_DAT="$TIMER_DATA_DIR/timer-enabled.dat"
TIMER_DURATION_DAT="$TIMER_DATA_DIR/timer-duration.dat"
TIMER_COLOR_DAT="$TIMER_DATA_DIR/timer-color.dat"
TIMER_STATE_DAT="$TIMER_DATA_DIR/timer-state.dat"

TIMER_DEFAULT_COLOR="#ff0000"
TIMER_DEFAULT_MINUTES=25
TIMER_MAX_MINUTES=999

# Stan wczytany przez timer_load_state (globalne, bo bash nie zwraca struktur)
TIMER_STATUS="stopped"   # stopped | running | paused | finished
TIMER_REMAINING=0        # sekundy — ważne dla stopped/paused/finished
TIMER_END=0              # epoch końca — ważny dla running
TIMER_NOTIFIED=0         # 1 = powiadomienie o zeru już poszło

# Wczytaj jedną wartość z pliku .dat, obcinając białe znaki (plik pisany
# ręcznie potrafi mieć \n, spacje, CR — ten sam zabieg co w volume-bar.sh).
_timer_read_dat() {
    local file="$1" val=""
    [[ -f "$file" ]] && val="$(<"$file")"
    val="${val//[[:space:]]/}"
    printf '%s' "$val"
}

# Czy moduł jest włączony w TUI? Domyślnie NIE — timer jest opcjonalny,
# świeża instalacja nie ma go na pasku, dopóki właściciel go nie włączy.
timer_enabled() {
    [[ "$(_timer_read_dat "$TIMER_ENABLED_DAT")" == "1" ]]
}

# Domyślne odliczanie w minutach (1..TIMER_MAX_MINUTES)
timer_duration_minutes() {
    local val; val="$(_timer_read_dat "$TIMER_DURATION_DAT")"
    if [[ "$val" =~ ^[0-9]+$ ]] && (( val >= 1 && val <= TIMER_MAX_MINUTES )); then
        printf '%s' "$val"
    else
        printf '%s' "$TIMER_DEFAULT_MINUTES"
    fi
}

# Kolor tekstu. Walidacja jest OBOWIĄZKOWA, nie kosmetyczna: wartość ląduje
# w markupie pango (<span color='...'>), więc byle co z pliku mogłoby rozbić
# renderowanie etykiety całego modułu.
timer_color() {
    local val; val="$(_timer_read_dat "$TIMER_COLOR_DAT")"
    if [[ "$val" =~ ^#[0-9a-fA-F]{6}$ ]]; then
        printf '%s' "$val"
    else
        printf '%s' "$TIMER_DEFAULT_COLOR"
    fi
}

# Wczytaj stan biegu do zmiennych TIMER_*. Format key=value, jedna para
# na linię — czytany pętlą, NIGDY przez `source` (plik danych nie jest kodem).
timer_load_state() {
    TIMER_STATUS="stopped"
    TIMER_REMAINING=$(( $(timer_duration_minutes) * 60 ))
    TIMER_END=0
    TIMER_NOTIFIED=0

    [[ -f "$TIMER_STATE_DAT" ]] || return 0

    local line key val
    while IFS= read -r line; do
        [[ "$line" == *"="* ]] || continue
        key="${line%%=*}"
        val="${line#*=}"
        key="${key//[[:space:]]/}"
        val="${val//[[:space:]]/}"
        case "$key" in
            status)    [[ "$val" =~ ^(stopped|running|paused|finished)$ ]] && TIMER_STATUS="$val" ;;
            remaining) [[ "$val" =~ ^[0-9]+$ ]] && TIMER_REMAINING="$val" ;;
            end)       [[ "$val" =~ ^[0-9]+$ ]] && TIMER_END="$val" ;;
            notified)  [[ "$val" == "1" ]] && TIMER_NOTIFIED=1 ;;
        esac
    done < "$TIMER_STATE_DAT"
    return 0
}

# Zapisz stan atomowo (tmp + mv) — ten sam wzorzec co przełącznik tapet
# i workspace-mode-switch.sh: moduł odpala się co sekundę i nie może
# przeczytać pliku w połowie zapisu.
timer_save_state() {
    mkdir -p "$TIMER_DATA_DIR" 2>/dev/null
    local tmp
    tmp="$(mktemp "${TIMER_STATE_DAT}.XXXXXX")" || return 1
    {
        echo "# generated by archenemy - stan timera waybara (custom/timer)"
        echo "status=$TIMER_STATUS"
        echo "remaining=$TIMER_REMAINING"
        echo "end=$TIMER_END"
        echo "notified=$TIMER_NOTIFIED"
    } > "$tmp"
    mv "$tmp" "$TIMER_STATE_DAT"
}

# Ile sekund zostało DO WYŚWIETLENIA. Dla running liczone z zegara ściennego
# (end - teraz), nie z odejmowania po tyknięciach: dzięki temu przeładowanie
# waybara, przełączenie rice'a czy zgubione tyknięcie niczego nie przesuwają.
timer_remaining_now() {
    local rem="$TIMER_REMAINING"
    if [[ "$TIMER_STATUS" == "running" ]]; then
        rem=$(( TIMER_END - $(date +%s) ))
    fi
    (( rem < 0 )) && rem=0
    printf '%s' "$rem"
}

# MM:SS z minutami dopełnionymi do dwóch cyfr. Powyżej 99 minut etykieta
# rośnie o cyfrę (np. 120:00) — świadomie, bo alternatywa (HH:MM:SS) zmienia
# format w locie. Szerokość modułu jest stała w typowym zakresie, więc
# wyśrodkowany zegar obok nie drga przy każdej sekundzie.
timer_format() {
    local total="$1"
    printf '%02d:%02d' $(( total / 60 )) $(( total % 60 ))
}
